#!/system/bin/sh
sync

# AOSP Debloater created by @VadaPavMan
# Github: https://github.com/VadaPavMan

echo "This Will Completely Remove Google Apps Services. 
(Pros: Less CPU And Memory Usage And Better Battery Life)"

UNINSTALLED_APPS=""
uninstall_and_record() {
  pm uninstall --user 0 $1
  if [ $? -eq 0 ]; then
    UNINSTALLED_APPS="$UNINSTALLED_APPS\n$1"
  fi
}

APPS_TO_UNINSTALL=(
android.romstats
androidx.compose.material.catalog
cci.usage
code.name.monkey.retromusic
com.amazon.aa
com.amazon.aa.attribution
com.amazon.appmanager
com.amazon.avod.thirdpartyclient
com.android.apps.tag
com.android.backupconfirm
com.android.bips
com.android.bluetoothmidiservice
com.android.bookmarkprovider
com.android.browser
com.android.calllogbackup
com.android.carrierdefaultapp
com.android.cellbroadcastreceiver
com.android.cellbroadcastreceiver.module
com.android.cellbroadcastservice
com.android.companiondevicemanager
com.android.cts.ctsshim
com.android.cts.priv.ctsshim
com.android.dreams.basic
com.android.dreams.phototable
com.android.dynsystem
com.android.egg
com.android.email
com.android.emergency
com.android.fmradio
com.android.hotwordenrollment.okgoogle
com.android.hotwordenrollment.xgoogle
com.android.imsserviceentitlement
com.android.magicsmoke
com.android.managedprovisioning
com.android.midrive
com.android.music
com.android.musicfx
com.android.noisefield
com.android.omadm.service
com.android.onetimeinitializer
com.android.ons
com.android.pacprocessor
com.android.phasebeam
com.android.printservice.recommendation
com.android.protips
com.android.providers.partnerbookmarks
com.android.providers.userdictionary
com.android.proxyhandler
com.android.quicksearchbox
com.android.sharedstoragebackup
com.android.shell.tombstoned
com.android.simappdialog
com.android.smspush
com.android.stk
com.android.systemui.plugin.globalactions.wallet
com.android.traceur
com.android.wallpaper.livepicker
com.android.wallpaperbackup
com.applovin.array.apphub.vincere
com.autonavi.minimap
com.caf.fmradio
com.chrome.canary
com.chrome.dev
com.coloros.backuprestore
com.coloros.bootreg
com.coloros.calculator
com.coloros.childrenspace
com.coloros.compass2
com.coloros.healthcheck
com.coloros.note
com.coloros.operationManual
com.coloros.oshare
com.coloros.smartsidebar
com.coloros.video
com.coloros.weather.service
com.coloros.weather2
com.crdoid.music
com.crdroid.updater
com.diotek.sec.lookup.dictionary
com.dsi.ant.plugins.antplus
com.dsi.ant.sample.acquirechannels
com.dsi.ant.server
com.dsi.ant.service.socket
com.duckduckgo.mobile.android
com.duokan.phone.remotecontroller
com.duokan.phone.remotecontroller.peel.plugin
com.eterno
com.eterno.shortvideos
com.facebook.appmanager
com.facebook.services
com.facebook.system
com.facemoji.lite.xiaomi
com.finshell.fin
com.glance.internet
com.google.ambient.streaming
com.google.android.accessibility.reader
com.google.android.accessibility.soundamplifier
com.google.android.apps.accessibility.auditor
com.google.android.apps.accessibility.maui.actionblocks
com.google.android.apps.accessibility.reveal
com.google.android.apps.accessibility.voiceaccess
com.google.android.apps.adm
com.google.android.apps.adwords
com.google.android.apps.books
com.google.android.apps.carrier.log
com.google.android.apps.chromecast.app
com.google.android.apps.cloudconsole
com.google.android.apps.cloudprint
com.google.android.apps.currents
com.google.android.apps.dynamite
com.google.android.apps.enterprise.cpanel
com.google.android.apps.fitness
com.google.android.apps.gcs
com.google.android.apps.giant
com.google.android.apps.googleassistant
com.google.android.apps.googlevoice
com.google.android.apps.healthdata
com.google.android.apps.helprtc
com.google.android.apps.jam
com.google.android.apps.kids.familylink
com.google.android.apps.magazines
com.google.android.apps.meetings
com.google.android.apps.nbu.files
com.google.android.apps.nbu.paisa.user
com.google.android.apps.photos.scanner
com.google.android.apps.photosgo
com.google.android.apps.pixelmigrate
com.google.android.apps.playconsole
com.google.android.apps.plus
com.google.android.apps.podcasts
com.google.android.apps.recorder
com.google.android.apps.restore
com.google.android.apps.safetyhub
com.google.android.apps.setupwizard.searchselector
com.google.android.apps.subscriptions.red
com.google.android.apps.tachyon
com.google.android.apps.tasks
com.google.android.apps.turbo
com.google.android.apps.tycho
com.google.android.apps.village.boond
com.google.android.apps.walletnfcrel
com.google.android.apps.weather
com.google.android.apps.wellbeing
com.google.android.apps.wifisetup.app
com.google.android.apps.work.clouddpc
com.google.android.apps.youtube.kids
com.google.android.as
com.google.android.as.oss
com.google.android.configupdater
com.google.android.email
com.google.android.ext.shared
com.google.android.feedback
com.google.android.gm.exchange
com.google.android.gms.location.history
com.google.android.gms.policy_sidecar_aps
com.google.android.googlequicksearchbox
com.google.android.ims
com.google.android.marvin.talkback
com.google.android.music
com.google.android.odad
com.google.android.onetimeinitializer
com.google.android.partnersetup
com.google.android.pixel.setupwizard
com.google.android.printservice.recommendation
com.google.android.projection.gearhead
com.google.android.setupwizard
com.google.android.tag
com.google.android.talk
com.google.android.tts
com.google.android.videos
com.google.android.webview.beta
com.google.android.webview.canary
com.google.android.webview.dev
com.google.android.wfcactivation
com.google.ar.core
com.google.ar.lens
com.google.audio.hearing.visualization.accessibility.scribe
com.google.earth
com.google.location.nearby.apps.fastpair.validator
com.google.mainline.telemetry
com.google.samples.apps.cardboarddemo
com.google.tango.measure
com.hampusolsson.abstruct
com.havoc.browser
com.heytap.browser
com.heytap.cloud
com.heytap.colorfulengine
com.heytap.market
com.heytap.music
com.heytap.pictorial
com.heytap.usercenter
com.iven.musicplayergo
com.kabouzeid.gramophone.mokee
com.lenovo.lsf.user
com.libremobileos.desktopmode
com.libremobileos.etar
com.libremobileos.faceunlock
com.libremobileos.parallelspace
com.libremobileos.recorder
com.libremobileos.setupwizard
com.microsoft.appmanager
com.microsoft.office.officehubrow
com.microsoft.skydrive
com.mokee.center
com.mokee.gallery
com.nearme.gamecenter
com.netflix.partner.activation
com.opera.max.oem
com.opera.preinstall
com.orange.update
com.phonepe.app
com.qti.dpmserviceapp
com.qti.qualcomm.datastatusnotification
com.qualcomm.atfwd
com.qualcomm.embms
com.qualcomm.qti.perfdump
com.qualcomm.qti.uim
com.redteamobile.roaming
com.simplemobiletools.gallery.pro
com.stevesoltys.seedvault
com.swiftkey.swiftkeyconfigurator
com.syberia.SyberiaPapers
com.syberia.ota
com.tencent.soter.soterserver
com.verizon.loginengi
com.yandex.browser
de.axelspringer.yana.zeropage
flipboard.boxer.app
in.amazon.mShop.android.shopping
org.akanework.gramophone
org.chromium.webview_shell
org.lineageos.audiofx
org.lineageos.eleven
org.lineageos.jelly
org.lineageos.recorder
org.omnirom.logcat
ru.yandex.disk
ru.yandex.searchplugin
ru.yandex.yandexmaps
android.qvaoverlay.common
com.android.adservices.api
com.android.apps.tag
com.android.backupconfirm
com.android.bips
com.android.bluetoothmidiservice
com.android.calllogbackup
com.android.cameraextensions
com.android.carrierdefaultapp
com.android.cellbroadcastreceiver
com.android.cellbroadcastreceiver.overlay.common
com.android.cellbroadcastservice
com.android.companiondevicemanager
com.android.cts.ctsshim
com.android.cts.priv.ctsshim
com.android.dreams.basic
com.android.dynsystem
com.android.egg
com.android.emergency
com.android.fmradio
com.android.incallui.overlay
com.android.managedprovisioning
com.android.managedprovisioning.overlay
com.android.ondevicepersonalization.services
com.android.ons
com.android.overlay.gmscontactprovider
com.android.overlay.gmssettingprovider
com.android.overlay.gmssettings
com.android.overlay.gmstelecomm
com.android.overlay.gmstelephony
com.android.packageinstaller
com.android.pacprocessor
com.android.providers.userdictionary
com.android.proxyhandler
com.android.quicksearchbox
com.android.remoteprovisioner
com.android.safetycenter.resources
com.android.sharedstoragebackup
com.android.simappdialog
com.android.smspush
com.android.stk
com.android.stk.overlay.miui
com.android.systemui.overlay.common
com.android.systemui.overlay.miui
com.android.theme.font.notoserifsource
com.android.traceur
com.android.wallpaper.livepicker
com.android.wallpaperbackup
com.bsp.catchlog
com.goodix.fingerprint.setting
com.google.android.cellbroadcastreceiver.overlay.miui
com.google.android.cellbroadcastservice.overlay.miui
com.google.android.configupdater
com.google.android.ext.shared
com.google.android.gms.location.history
com.google.android.marvin.talkback
com.google.android.onetimeinitializer
com.google.android.printservice.recommendation
com.milink.service
com.miui.accessibility
com.miui.audioeffect
com.miui.backup
com.miui.bugreport
com.miui.carlink
com.miui.catcherpatch
com.miui.cit
com.miui.cloudbackup
com.miui.cloudservice
com.miui.contentcatcher
com.miui.contentextension
com.miui.daemon
com.miui.fmservice
com.miui.greenguard
com.miui.maintenancemode
com.miui.micloudsync
com.miui.miservice
com.miui.miwallpaper.overlay.customize
com.miui.nextpay
com.miui.otaprovision
com.miui.personalassistant
com.miui.phrase
com.miui.qr
com.miui.securityinputmethod
com.miui.settings.rro.device.hide.statusbar.overlay
com.miui.settings.rro.device.type.overlay
com.miui.system.overlay
com.miui.touchassistant
com.miui.translation.kingsoft
com.miui.translation.xmcloud
com.miui.translationservice
com.miui.tsmclient
com.miui.uireporter
com.miui.voiceassist
com.miui.voiceassistoverlay
com.miui.voicetrigger
com.miui.vpnsdkmanager
com.miui.vsimcore
com.miui.wallpaper.overlay.customize
com.miui.wmsvc
com.miui.yellowpage
com.miuix.editor
com.mobiletools.systemhelper
com.modemdebug
com.qti.dcf
com.qti.diagservices
com.qti.dpmserviceapp
com.qti.qcc
com.qti.qualcomm.datastatusnotification
com.qti.qualcomm.deviceinfo
com.qti.service.colorservice
com.qti.snapdragon.qdcm_ff
com.qualcomm.atfwd
com.qualcomm.embms
com.qualcomm.location
com.qualcomm.qti.autoregistration
com.qualcomm.qti.devicestatisticsservice
com.qualcomm.qti.performancemode
com.qualcomm.qti.powersavemode
com.qualcomm.qti.qcolor
com.qualcomm.qti.remoteSimlockAuth
com.qualcomm.qti.ridemodeaudio
com.qualcomm.qti.server.qtiwifi
com.qualcomm.qti.uim
com.qualcomm.qti.uimGbaApp
com.qualcomm.qti.xrcb
com.qualcomm.uimremoteclient
com.qualcomm.uimremoteserver
com.quicinc.voice.activation
com.rongcard.eid
com.rongcard.eidapi
com.sohu.inputmethod.sogou.xiaomi
com.tencent.soter.soterserver
com.unionpay.tsmservice.mi
com.wapi.wapicertmanage
com.xiaomi.aiasst.service
com.xiaomi.aiasst.vision
com.xiaomi.aicr
com.xiaomi.aireco
com.xiaomi.cameratools
com.xiaomi.digitalkey
com.xiaomi.gamecenter.sdk.service
com.xiaomi.location.fused
com.xiaomi.macro
com.xiaomi.metoknlp
com.xiaomi.mi_connect_service
com.xiaomi.micloud.sdk
com.xiaomi.mirror
com.xiaomi.mtb
com.xiaomi.NetworkBoost
com.xiaomi.otrpbroker
com.xiaomi.payment
com.xiaomi.security.onetrack
com.xiaomi.simactivate.service
com.xiaomi.xaee
com.xiaomi.xmsfkeeper
org.ifaa.aidl.manager
org.mipay.android.manager
)

for APP in "${APPS_TO_UNINSTALL[@]}"; do
  uninstall_and_record $APP
done

echo "• THE FOLLOWING APPS WERE UNINSTALLED:"
echo -e $UNINSTALLED_APPS
echo "• REBOOT YOUR DEVICE."